# generated by datamodel-codegen:
#   filename:  scratch_5.json
#   timestamp: 2022-03-01T14:10:44+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Reference(BaseModel):
    mscnumber: str


class Period(BaseModel):
    period: str
    update: str


class Billingunit(BaseModel):
    reference: Reference
    periods: List[Period]


class PeriodResponse(BaseModel):
    billingunit: Billingunit
