name: Code Quality

on: push

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Run pre-commit hook
        run: |
          pip install pre-commit
          pre-commit install
          pre-commit run --all-files
